name: Build, Push and Deploy Webapp

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NAMESPACE: escape-nation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      repo-lc: ${{ steps.vars.outputs.repo-lc }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit to check for changes

      - name: Check if webapp directory has changes
        id: changes
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, building webapp..."
            echo "webapp_changed=true" >> $GITHUB_OUTPUT
          else
            # Check if webapp directory has changes between previous tag and current tag
            if git diff --name-only $PREV_TAG..HEAD | grep -q "^webapp/"; then
              echo "Webapp directory has changes, building..."
              echo "webapp_changed=true" >> $GITHUB_OUTPUT
            else
              echo "No changes in webapp directory, skipping build"
              echo "webapp_changed=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Set lowercase repository name
        id: vars
        if: steps.changes.outputs.webapp_changed == 'true'
        run: |
          echo "repo-lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Extract tag name
        id: tag
        if: steps.changes.outputs.webapp_changed == 'true'
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.changes.outputs.webapp_changed == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Log in to the Container registry
        if: steps.changes.outputs.webapp_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        if: steps.changes.outputs.webapp_changed == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.vars.outputs.repo-lc }}-webapp
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        if: steps.changes.outputs.webapp_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./webapp
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Skip build notification
        if: steps.changes.outputs.webapp_changed == 'false'
        run: |
          echo "⏭️ Skipping webapp build - no changes detected in webapp/ directory"