name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: linux-amd64
          - goos: linux
            goarch: arm64
            suffix: linux-arm64
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64
          - goos: windows
            goarch: amd64
            suffix: windows-amd64.exe
          - goos: windows
            goarch: arm64
            suffix: windows-arm64.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build CLI
        working-directory: cli
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o shipyard-${{ matrix.suffix }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shipyard-${{ matrix.suffix }}
          path: cli/shipyard-${{ matrix.suffix }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create installation scripts
        run: |
          # Create install script for Unix (Linux/macOS)
          cat > install.sh << 'EOF'
          #!/bin/bash
          set -e
          
          # Shipyard CLI Installer with k3s
          # Usage: curl -sSL https://github.com/CodeAlchemyFr/shipyard/releases/latest/download/install.sh | bash
          
          REPO="CodeAlchemyFr/shipyard"
          INSTALL_DIR="/usr/local/bin"
          BINARY_NAME="shipyard"
          INSTALL_K3S=${INSTALL_K3S:-true}
          
          # Colors for output
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          YELLOW='\033[1;33m'
          BLUE='\033[0;34m'
          NC='\033[0m' # No Color
          
          echo -e "${BLUE}🚀 Installing Shipyard CLI with k3s...${NC}"
          
          # Detect OS and architecture
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          
          case $ARCH in
            x86_64) ARCH="amd64" ;;
            arm64|aarch64) ARCH="arm64" ;;
            armv7l) ARCH="arm" ;;
            *) echo -e "${RED}❌ Unsupported architecture: $ARCH${NC}"; exit 1 ;;
          esac
          
          case $OS in
            linux) PLATFORM="linux" ;;
            darwin) PLATFORM="darwin" ;;
            *) echo -e "${RED}❌ Unsupported OS: $OS${NC}"; exit 1 ;;
          esac
          
          BINARY_URL="https://github.com/${REPO}/releases/latest/download/shipyard-${PLATFORM}-${ARCH}"
          
          echo -e "${YELLOW}📋 Detected platform: ${PLATFORM}-${ARCH}${NC}"
          echo -e "${YELLOW}📦 Downloading from: ${BINARY_URL}${NC}"
          
          # Create temp directory
          TMP_DIR=$(mktemp -d)
          trap 'rm -rf $TMP_DIR' EXIT
          
          # Download binary
          if command -v curl >/dev/null 2>&1; then
            curl -sSL -o "$TMP_DIR/$BINARY_NAME" "$BINARY_URL"
          elif command -v wget >/dev/null 2>&1; then
            wget -qO "$TMP_DIR/$BINARY_NAME" "$BINARY_URL"
          else
            echo -e "${RED}❌ Neither curl nor wget found. Please install one of them.${NC}"
            exit 1
          fi
          
          # Check if download was successful
          if [ ! -f "$TMP_DIR/$BINARY_NAME" ]; then
            echo -e "${RED}❌ Failed to download Shipyard CLI${NC}"
            exit 1
          fi
          
          # Make binary executable
          chmod +x "$TMP_DIR/$BINARY_NAME"
          
          # Install binary
          if [ -w "$INSTALL_DIR" ]; then
            mv "$TMP_DIR/$BINARY_NAME" "$INSTALL_DIR/$BINARY_NAME"
          else
            echo -e "${YELLOW}🔑 Installing to $INSTALL_DIR (requires sudo)${NC}"
            sudo mv "$TMP_DIR/$BINARY_NAME" "$INSTALL_DIR/$BINARY_NAME"
          fi
          
          echo -e "${GREEN}✅ Shipyard CLI installed successfully!${NC}"
          
          # Install k3s if requested
          if [ "$INSTALL_K3S" = "true" ]; then
            echo -e "${BLUE}🐳 Installing k3s...${NC}"
            
            # Check if k3s is already installed
            if command -v k3s >/dev/null 2>&1; then
              echo -e "${YELLOW}⚠️  k3s is already installed: $(k3s --version | head -1)${NC}"
            else
              # Install k3s
              if [ "$OS" = "linux" ]; then
                echo -e "${YELLOW}📦 Downloading k3s installer...${NC}"
                curl -sfL https://get.k3s.io | sh -
                
                # Wait for k3s to be ready
                echo -e "${YELLOW}⏳ Waiting for k3s to be ready...${NC}"
                sudo k3s kubectl wait --for=condition=ready node --all --timeout=60s 2>/dev/null || true
                
                # Set up kubeconfig for current user
                mkdir -p ~/.kube
                sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
                sudo chown $(id -u):$(id -g) ~/.kube/config
                
                # Also fix permissions on the original file
                sudo chmod 644 /etc/rancher/k3s/k3s.yaml
                
                # Set KUBECONFIG environment variable permanently
                export KUBECONFIG=~/.kube/config
                
                # Detect shell and add to appropriate config file
                SHELL_NAME=$(basename "$SHELL")
                case "$SHELL_NAME" in
                  bash)
                    echo 'export KUBECONFIG=~/.kube/config' >> ~/.bashrc
                    echo -e "${YELLOW}📝 Added KUBECONFIG to ~/.bashrc${NC}"
                    ;;
                  zsh)
                    echo 'export KUBECONFIG=~/.kube/config' >> ~/.zshrc
                    echo -e "${YELLOW}📝 Added KUBECONFIG to ~/.zshrc${NC}"
                    ;;
                  fish)
                    mkdir -p ~/.config/fish
                    echo 'set -gx KUBECONFIG ~/.kube/config' >> ~/.config/fish/config.fish
                    echo -e "${YELLOW}📝 Added KUBECONFIG to ~/.config/fish/config.fish${NC}"
                    ;;
                  *)
                    echo 'export KUBECONFIG=~/.kube/config' >> ~/.profile
                    echo -e "${YELLOW}📝 Added KUBECONFIG to ~/.profile (generic shell: $SHELL_NAME)${NC}"
                    ;;
                esac
                
                # For current session, use the copied config
                export KUBECONFIG=~/.kube/config
                
                echo -e "${GREEN}✅ k3s installed and configured successfully!${NC}"
                echo -e "${BLUE}📋 k3s cluster info: $(k3s kubectl cluster-info | head -1)${NC}"
                
                # Install cert-manager for SSL certificates
                echo -e "${BLUE}🔐 Installing cert-manager for SSL certificates...${NC}"
                kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml
                
                # Wait for cert-manager to be ready
                echo -e "${YELLOW}⏳ Waiting for cert-manager to be ready...${NC}"
                kubectl wait --for=condition=ready pod -l app=cert-manager -n cert-manager --timeout=300s 2>/dev/null || true
                kubectl wait --for=condition=ready pod -l app=cainjector -n cert-manager --timeout=300s 2>/dev/null || true
                kubectl wait --for=condition=ready pod -l app=webhook -n cert-manager --timeout=300s 2>/dev/null || true
                
                # Wait a bit more for webhook to be fully available
                echo -e "${YELLOW}⏳ Waiting for cert-manager webhook to be available...${NC}"
                sleep 30
                
                # Create Let's Encrypt ClusterIssuer
                echo -e "${BLUE}📄 Creating Let's Encrypt ClusterIssuer...${NC}"
                echo -e "${YELLOW}📧 Please provide an email for Let's Encrypt certificates:${NC}"
                read -p "Email: " SSL_EMAIL
                cat <<ISSUER_EOF | kubectl apply -f -
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-prod
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: \${SSL_EMAIL}
              privateKeySecretRef:
                name: letsencrypt-prod
              solvers:
              - http01:
                  ingress:
                    class: traefik
          ISSUER_EOF
                
                echo -e "${GREEN}✅ SSL stack (cert-manager + ClusterIssuer) installed successfully!${NC}"
              elif [ "$OS" = "darwin" ]; then
                echo -e "${YELLOW}🍎 On macOS, k3s must run in Docker. Installing k3d instead...${NC}"
                
                # Install k3d (k3s in docker)
                if command -v docker >/dev/null 2>&1; then
                  curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
                  
                  # Create a k3s cluster
                  k3d cluster create shipyard --port "8080:80@loadbalancer" --port "8443:443@loadbalancer"
                  
                  echo -e "${GREEN}✅ k3d cluster 'shipyard' created successfully!${NC}"
                  echo -e "${BLUE}📋 Access your cluster with: kubectl cluster-info${NC}"
                else
                  echo -e "${RED}❌ Docker is required for k3s on macOS. Please install Docker first.${NC}"
                  echo -e "${YELLOW}📚 Install Docker: https://docs.docker.com/desktop/mac/install/${NC}"
                fi
              fi
            fi
          else
            echo -e "${YELLOW}⏭️  Skipping k3s installation (set INSTALL_K3S=false to disable)${NC}"
          fi
          
          echo -e "${BLUE}📖 Get started with: shipyard --help${NC}"
          echo -e "${BLUE}📚 Documentation: https://codealchemy.github.io/shipyard/${NC}"
          
          # Verify installation
          if command -v shipyard >/dev/null 2>&1; then
            echo -e "${GREEN}🎉 Installation verified: $(shipyard --version)${NC}"
          else
            echo -e "${YELLOW}⚠️  Please add $INSTALL_DIR to your PATH or restart your terminal${NC}"
          fi
          
          # Shell-specific restart instructions
          SHELL_NAME=$(basename "$SHELL")
          echo ""
          echo -e "${BLUE}📝 To use kubectl immediately in this session:${NC}"
          echo -e "${YELLOW}   export KUBECONFIG=~/.kube/config${NC}"
          echo ""
          echo -e "${BLUE}📝 Or restart your terminal to load the new environment variables.${NC}"
          echo -e "${BLUE}🔄 Your shell config has been updated for future sessions (${SHELL_NAME}).${NC}"
          EOF
          
          # Create install script for Windows (PowerShell)
          cat > install.ps1 << 'EOF'
          # Shipyard CLI Installer for Windows with k3s
          # Usage: Invoke-WebRequest -Uri "https://github.com/CodeAlchemyFr/shipyard/releases/latest/download/install.ps1" -OutFile "install.ps1"; .\install.ps1
          
          $ErrorActionPreference = "Stop"
          
          $REPO = "CodeAlchemyFr/shipyard"
          $INSTALL_DIR = "$env:USERPROFILE\bin"
          $BINARY_NAME = "shipyard.exe"
          $INSTALL_K3S = if ($env:INSTALL_K3S) { $env:INSTALL_K3S } else { "true" }
          
          Write-Host "🚀 Installing Shipyard CLI with k3s..." -ForegroundColor Blue
          
          # Detect architecture
          $ARCH = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
          if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { $ARCH = "arm64" }
          
          $BINARY_URL = "https://github.com/$REPO/releases/latest/download/shipyard-windows-$ARCH.exe"
          
          Write-Host "📋 Detected platform: windows-$ARCH" -ForegroundColor Yellow
          Write-Host "📦 Downloading from: $BINARY_URL" -ForegroundColor Yellow
          
          # Create install directory
          if (!(Test-Path $INSTALL_DIR)) {
              New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null
          }
          
          $BINARY_PATH = Join-Path $INSTALL_DIR $BINARY_NAME
          
          try {
              # Download binary
              Invoke-WebRequest -Uri $BINARY_URL -OutFile $BINARY_PATH
              
              Write-Host "✅ Shipyard CLI installed successfully!" -ForegroundColor Green
              
              # Install k3s if requested
              if ($INSTALL_K3S -eq "true") {
                  Write-Host "🐳 Installing k3s on Windows..." -ForegroundColor Blue
                  
                  # Check if Docker Desktop is running
                  $dockerRunning = $false
                  try {
                      docker info | Out-Null
                      $dockerRunning = $true
                  } catch {
                      $dockerRunning = $false
                  }
                  
                  if ($dockerRunning) {
                      # Check if k3d is already installed
                      $k3dInstalled = $false
                      try {
                          k3d version | Out-Null
                          $k3dInstalled = $true
                          Write-Host "⚠️ k3d is already installed" -ForegroundColor Yellow
                      } catch {
                          Write-Host "📦 Installing k3d (k3s in Docker)..." -ForegroundColor Yellow
                          
                          # Download and install k3d
                          $k3dUrl = "https://github.com/k3d-io/k3d/releases/latest/download/k3d-windows-amd64.exe"
                          $k3dPath = Join-Path $INSTALL_DIR "k3d.exe"
                          Invoke-WebRequest -Uri $k3dUrl -OutFile $k3dPath
                          
                          Write-Host "✅ k3d installed successfully!" -ForegroundColor Green
                          $k3dInstalled = $true
                      }
                      
                      if ($k3dInstalled) {
                          # Create k3s cluster
                          Write-Host "🏗️ Creating k3s cluster 'shipyard'..." -ForegroundColor Yellow
                          try {
                              & k3d cluster create shipyard --port "8080:80@loadbalancer" --port "8443:443@loadbalancer" 2>$null
                              Write-Host "✅ k3d cluster 'shipyard' created successfully!" -ForegroundColor Green
                              Write-Host "📋 Access your cluster with: kubectl cluster-info" -ForegroundColor Blue
                          } catch {
                              Write-Host "⚠️ k3s cluster may already exist or Docker needs restart" -ForegroundColor Yellow
                          }
                      }
                  } else {
                      Write-Host "❌ Docker Desktop is required for k3s on Windows." -ForegroundColor Red
                      Write-Host "📚 Please install Docker Desktop: https://docs.docker.com/desktop/windows/install/" -ForegroundColor Yellow
                      Write-Host "🔄 After installing Docker, rerun this script to install k3s" -ForegroundColor Yellow
                  }
              } else {
                  Write-Host "⏭️ Skipping k3s installation (set `$env:INSTALL_K3S=`"false`" to disable)" -ForegroundColor Yellow
              }
              
              Write-Host "📖 Get started with: shipyard --help" -ForegroundColor Blue
              Write-Host "📚 Documentation: https://codealchemy.github.io/shipyard/" -ForegroundColor Blue
              
              # Add to PATH if not already there
              $currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
              if ($currentPath -notlike "*$INSTALL_DIR*") {
                  [Environment]::SetEnvironmentVariable("PATH", "$currentPath;$INSTALL_DIR", "User")
                  Write-Host "🔄 Added $INSTALL_DIR to your PATH. Please restart your terminal." -ForegroundColor Yellow
              }
              
              # Verify installation
              & $BINARY_PATH --version
              Write-Host "🎉 Installation verified!" -ForegroundColor Green
              
          } catch {
              Write-Host "❌ Failed to install Shipyard CLI: $_" -ForegroundColor Red
              exit 1
          }
          EOF

      - name: Create checksums
        run: |
          # Generate checksums for all binaries
          find . -name "shipyard-*" -type f -exec sha256sum {} \; > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */shipyard-*
            install.sh
            install.ps1
            checksums.txt
          body: |
            ## 🚀 Shipyard CLI Release ${{ github.ref_name }}
            
            ### Installation
            
            #### Quick Install with k3s (Linux/macOS)
            ```bash
            curl -sSL https://github.com/CodeAlchemyFr/shipyard/releases/latest/download/install.sh | bash
            ```
            
            #### Quick Install with k3s (Windows PowerShell)
            ```powershell
            Invoke-WebRequest -Uri "https://github.com/CodeAlchemyFr/shipyard/releases/latest/download/install.ps1" -OutFile "install.ps1"; .\install.ps1
            ```
            
            #### Install without k3s
            ```bash
            # Linux/macOS
            INSTALL_K3S=false curl -sSL https://github.com/CodeAlchemyFr/shipyard/releases/latest/download/install.sh | bash
            
            # Windows PowerShell
            $env:INSTALL_K3S="false"; Invoke-WebRequest -Uri "https://github.com/CodeAlchemyFr/shipyard/releases/latest/download/install.ps1" -OutFile "install.ps1"; .\install.ps1
            ```
            
            #### Manual Installation
            
            1. Download the appropriate binary for your platform:
               - **Linux AMD64**: `shipyard-linux-amd64`
               - **Linux ARM64**: `shipyard-linux-arm64`
               - **macOS Intel**: `shipyard-darwin-amd64`
               - **macOS Apple Silicon**: `shipyard-darwin-arm64`
               - **Windows AMD64**: `shipyard-windows-amd64.exe`
               - **Windows ARM64**: `shipyard-windows-arm64.exe`
            
            2. Make it executable (Linux/macOS):
               ```bash
               chmod +x shipyard-*
               sudo mv shipyard-* /usr/local/bin/shipyard
               ```
            
            3. Verify installation:
               ```bash
               shipyard --version
               ```
            
            ### 📚 Documentation
            
            - [Getting Started](https://codealchemy.github.io/shipyard/getting-started)
            - [CLI Reference](https://codealchemy.github.io/shipyard/cli/overview)
            - [Deployment Guide](https://codealchemy.github.io/shipyard/guides/deployment)
            
            ### 🔐 Checksums
            
            All binaries are signed and checksums are provided in `checksums.txt`.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}